version: '3.8'
services:
  library-backend:
     container_name: librarybe
     image: anjardanis/library-be
     stdin_open: true
     ports:
       - 5000:5000
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: anjar
       MYSQL_DATABASE: library
       MYSQL_USER: backend
       MYSQL_PASSWORD: anjar
      ports:
        - 3306:3306
volumes:
  db_data: {}