FROM node:10-alpine

ARG NR_LICENSE_KEY

ARG NR_APP_NAME

ARG NR_ENABLED

ENV NEW_RELIC_NO_CONFIG_FILE=true \
    NEW_RELIC_ENABLED=$NR_ENABLED \
    NEW_RELIC_LICENSE_KEY=$NR_LICENSE_KEY \
    NEW_RELIC_APP_NAME=$NR_APP_NAME \ 
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=$NR_DT_ENABLED

ARG START_SCRIPT

ARG PORT

ENV START_COMMAND=$START_SCRIPT

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY . .

RUN npm install

RUN npm install -g sequelize-cli

# RUN sequelize db:migrate all

# RUN sequelize db:seed:all

EXPOSE $PORT

CMD npm run $START_COMMAND